### ISSUE TITLE
Windows Sandbox Installed, But Receiving OptionalFeature Attribute Error.

### ISSUE THREAD

**Issue by Ghostcrafter090** [karkason/pywinsandbox#16]
I have windows sandbox installed, however attempting to import thge library results in the error bellow:
`Traceback (most recent call last):
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\wmi.py", line 1209, in __getattr__
    return self._cached_classes(attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\wmi.py", line 1220, in _cached_classes
    self._classes_map[class_name] = _wmi_class(self, self._namespace.Get(class_name))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<COMObject winmgmts:>", line 2, in Get
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\client\dynamic.py", line 368, in _ApplyTypes_
    result = self._oleobj_.InvokeTypes(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'SWbemServicesEx', 'Not found ', None, 0, -2147217406), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\winsandbox\__init__.py", line 1, in <module>
    from .launch import new_sandbox, connect_to_sandbox
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\winsandbox\launch.py", line 9, in <module>
    verify_sandbox_feature_is_enabled()
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\winsandbox\utils\sandbox_feature_state.py", line 25, in verify_sandbox_feature_is_enabled
    if not is_sandbox_feature_enabled():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\winsandbox\utils\sandbox_feature_state.py", line 15, in is_sandbox_feature_enabled
    matching_features = wmi_client.Win32_OptionalFeature(Name=_WINDOWS_SANDBOX_FEATURE_NAME)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\wmi.py", line 1211, in __getattr__
    return getattr(self._namespace, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshp\AppData\Local\Programs\Python\Python311\Lib\site-packages\win32com\client\dynamic.py", line 639, in __getattr__
    raise AttributeError("%s.%s" % (self._username_, attr))
AttributeError: winmgmts:.Win32_OptionalFeature`

System:
Windows 10 64bit Version 10.0.19045.2728
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39)
AMD Ryzen 7 5700X 8-Core Processor
NVidia GeForce RTX 3060
32GB DDR4
512GB M.2 NVMe SSD

**Comment by karkason** [comment]
Hello. Was this ever resolved?
It looks like your Windows version does not have the Windows Sandbox feature and WMI could not find it.
